apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kwok-performance-test
  region: us-west-2
  version: "1.27"

# Minimalna konfiguracja managed node groups
managedNodeGroups:
  - name: primary-nodes
    instanceType: t3.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: false
    labels:
      role: worker
    tags:
      Project: "KWOK-Performance-Test"
      Environment: "Testing"

# Tylko podstawowe addons (bez IAM service accounts)
addons:
  - name: vpc-cni
  - name: coredns  
  - name: kube-proxy

